import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dariusz Jendryczka Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-mono'>DiagTech</h1>
            <ul className=' flex items-center'>
              <li><BsFillMoonStarsFill className=' cursor-pointer text-2xl'/></li>
              <li><a className=' bg-orange-600 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div>
            <h2>Dariusz Jendryczka</h2>
            <h3>Frontend Developer</h3>
            <p>Freelancer providing services in frontend.</p>
          </div>
        </section>
      </main>

    </div>
  )
}
